development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: lims
  suffix: repo
  username: gibo
  password: amin9090!
test:
  <<: *development
  suffix: test

production:
  production:
  <<: *development
  protocol: 'http'
