development: &development
  protocol: 'http'
  host: 192.168.12.89
  port: 5984
  prefix: lims
  suffix: repo
  username: root
  password: password
test:
  <<: *development
  suffix: test

production:
  <<: *development
  protocol: 'http'
